In [6]:
import pandas as pd
import numpy as np
from numpy.linalg import cholesky
from scipy.stats import norm, matrix_normal, multivariate_normal

%matplotlib inline

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [7]:
np.random.seed(123)

In [8]:
# covariance matrix for each row
M = np.array([[1,.2], [.2,2]]); M
# cholesky(M)
N = 7
m = np.array([-1,2]); m

array([-1,  2])

In [9]:
# each row is distributed as a multivariate Normal
multivariate_normal.rvs(cov=M)

array([ 0.66718227, -1.70699631])

In [10]:
# Generate a matrix Y where each row is distributed as a multivariate Normal
Y = multivariate_normal.rvs(cov=M, size=N); Y

array([[-1.37394628,  0.67604909],
       [ 1.43387925, -1.11742566],
       [-1.06818943, -3.32268126],
       [-0.49274514,  1.93556751],
       [-0.27449164, -0.93423936],
       [-0.21249595,  2.20940603],
       [-0.53809517, -0.54192286]])

In [11]:
# Find the logpdf of the data Y, which is defined by the sum of the logpodf of each row
lpdf = np.sum(multivariate_normal.logpdf(Y,
                                         mean = m,
                                         cov=M)); lpdf

-34.16233067298012

In [12]:
# Equivalent to the logpdf of the following matrix normal
matrix_normal.logpdf(Y,
                     mean= np.tile(m, N).reshape((N,2)),
                     rowcov=np.eye(N),
                     colcov=M)

-34.16233067298012

In [13]:
# Equivalent to the logpdf of the following vectorized multivariate normal
C = np.kron(np.eye(N), M)
multivariate_normal.logpdf(Y.flatten(),
                           mean = np.tile(m, N),
                           cov=C)

-34.16233067298012