# Matrix Normal for vectorized calculation

## 1. Common $\mu$
If we have $N$ observations of the formt $y_i \sim N(\mu, C) $ we can compute 
$$ \log p(Y | \mu, C) = \sum \log p(y_i | \mu, C) $$ using the matrix normal form 

In [1]:
import pandas as pd
import numpy as np
from numpy.linalg import cholesky
from scipy.stats import norm, matrix_normal, multivariate_normal

%matplotlib inline

%load_ext autoreload
%autoreload 2

In [2]:
np.random.seed(123)

In [3]:
# covariance matrix for each row
M = np.array([[1,.2], [.2,2]]); M
# cholesky(M)
N = 7
m = np.array([-1,2]); m

array([-1,  2])

In [4]:
# each row is distributed as a multivariate Normal
multivariate_normal.rvs(cov=M)

array([ 0.66718227, -1.70699631])

In [5]:
# Generate a matrix Y where each row is distributed as a multivariate Normal
Y = multivariate_normal.rvs(cov=M, size=N); Y

array([[-1.37394628,  0.67604909],
       [ 1.43387925, -1.11742566],
       [-1.06818943, -3.32268126],
       [-0.49274514,  1.93556751],
       [-0.27449164, -0.93423936],
       [-0.21249595,  2.20940603],
       [-0.53809517, -0.54192286]])

In [6]:
# Find the logpdf of the data Y, which is defined by the sum of the logpodf of each row
lpdf = np.sum(multivariate_normal.logpdf(Y,
                                         mean = m,
                                         cov=M)); lpdf

-34.16233067298012

In [7]:
# Equivalent to the logpdf of the following matrix normal
matrix_normal.logpdf(Y,
                     mean= np.tile(m, N).reshape((N,2)),
                     rowcov=np.eye(N),
                     colcov=M)

-34.16233067298012

In [8]:
# Equivalent to the logpdf of the following vectorized multivariate normal
C = np.kron(np.eye(N), M)
multivariate_normal.logpdf(Y.flatten(),
                           mean = np.tile(m, N),
                           cov=C)

-34.16233067298012

## 2. Different $\mu_i$ for each row 

If we have $N$ observations of the formt $y_i \sim N(\mu_i, C) $ we can compute 
$$ \log p(Y | \mu, C) = \sum \log p(y_i | \mu_i, C) $$ using the matrix normal form 

In [9]:
# Generate a matrix mm which will be the mean mu_i of each row of data.
mm = multivariate_normal.rvs(cov=M, size=N); mm

array([[ 2.70117281,  2.68722774],
       [ 0.64293931,  1.33607728],
       [ 1.63445666,  0.75736757],
       [ 0.8794823 , -1.53007685],
       [-0.95261484, -1.63968777],
       [-1.13069981,  1.53668538],
       [-0.86756802, -0.03658182]])

In [10]:
# Find the logpdf of the data Y, which is defined by the sum of the logpodf of each row
lps = np.empty(N)
for i in range(N):
    lps[i] = multivariate_normal.logpdf(Y[i],
                                         mean = mm[i],
                                         cov=M)

lpdf = np.sum(lps); lpdf

-38.23246823539996

In [11]:
# Equivalent to the logpdf of the following matrix normal
matrix_normal.logpdf(Y,
                     mean= mm,
                     rowcov=np.eye(N),
                     colcov=M)

-38.23246823539996